name: CI/CD using github actions & ipo-alarm-app

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # JDK Setting
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: deploy to server
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: github.ref == 'refs/heads/main'
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME_GCP }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/rlawogur816/IPOAlarm
            ls -al
            sudo docker ps
            sudo docker stop ipo-alarm-app
            sudo docker rm ipo-alarm-app
            sudo git pull origin main
            sudo docker build -t ipo-alarm-vm:latest .
            sudo docker run -d -it -p 8080:8080 --name ipo-alarm-app \
            --env-file ./.env \
            ipo-alarm-vm:latest
            
            sudo docker exec ipo-alarm-app printenv
            sudo docker image prune -f

